apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kueue
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/devam1402/cloud-native-inference-platform.git
    targetRevision: main
    path: gitops/vendor
    directory:
      include: 'kueue-v0.19.2-manifests.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: kueue-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
