resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: asia-south1-docker.pkg.dev/cnip-platform-v2/cnip-images/cloud-native-inference-platform
  digest: sha256:7c8b454e3366c0349e57a7396fc55c0b10f243f5e6f3fe723c0ccf5186037def
